"""
Pharma Trend Digest Viewer — Streamlit app

Read-only viewer for the digests already generated by the GitHub Actions
workflow. Makes ZERO Anthropic API calls — it only reads markdown files
already sitting in the digests/ folder. Free to run, free to deploy on
Streamlit Community Cloud.

Run locally:
    pip install streamlit
    streamlit run streamlit_app.py

Deploy free: see the "Deploying this viewer" section in README.md.
"""

import re
from pathlib import Path

import streamlit as st

DIGEST_DIR = Path(__file__).parent / "digests"

st.set_page_config(page_title="Pharma Trend Digest", layout="wide")
st.title("Pharma Trend Digest")
st.caption(
    "Viewer only — this reads digests already produced by the monthly "
    "GitHub Actions run. Opening this page never costs anything."
)

digest_files = sorted(DIGEST_DIR.glob("digest-*.md"), reverse=True)

if not digest_files:
    st.info(
        "No digests yet. Either the monthly workflow hasn't run, or "
        "this app isn't pointed at the right repo. Trigger a manual "
        "run from the GitHub Actions tab, then reload this page."
    )
    st.stop()

dates = [f.stem.replace("digest-", "") for f in digest_files]
selected_date = st.sidebar.selectbox("Month", dates)
selected_file = DIGEST_DIR / f"digest-{selected_date}.md"
content = selected_file.read_text()

# Digest files are structured as:
#   # Pharma Trend Digest — DATE
#
#   ## Topic Name
#   ...body...
#
#   ---
#
#   ## Next Topic
#   ...body...
#
# Split on "\n## " to pull out each topic section cleanly, regardless
# of the "---" separators the agent inserts between sections.
raw_sections = re.split(r"\n## ", content)
header = raw_sections[0].strip()
topic_blocks = raw_sections[1:]

topics = []
for block in topic_blocks:
    block = re.sub(r"\n+---\s*$", "", block).strip()
    name, _, body = block.partition("\n")
    topics.append((name.strip(), body.strip()))

topic_names = [name for name, _ in topics]

st.sidebar.markdown("---")
selected_topics = st.sidebar.multiselect(
    "Topics shown", topic_names, default=topic_names
)

search_term = st.sidebar.text_input("Search within this digest")

st.sidebar.markdown("---")
st.sidebar.download_button(
    "Download this digest (.md)",
    data=content,
    file_name=selected_file.name,
    mime="text/markdown",
)

st.markdown(header)
st.markdown("")

any_shown = False
for name, body in topics:
    if name not in selected_topics:
        continue
    if search_term and search_term.lower() not in (name + body).lower():
        continue
    any_shown = True
    with st.expander(name, expanded=True):
        st.markdown(body)

if not any_shown:
    st.warning("Nothing matches the current topic/search filters.")
